### ISSUE TITLE
你好，请问你有没有mxshop-api对应yapi文件

### ISSUE THREAD

**Issue by bubbleboy11** [myboran/mxshop-api#1]

**Comment by myboran** [comment]
不好意思，当时部署yapi的时候安装出错了，就没生成

**Comment by bubbleboy11** [comment]
刚刚有个老哥分享的，不知道你还需不需要
「api.json」，点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载，极速在线查看享用。
链接：https://www.aliyundrive.com/s/Gac23bnJqrj

**Comment by myboran** [comment]
好的，谢谢
